apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: demucs-rest
spec:
  selector:
    matchLabels:
      app: demucs-rest
  replicas: 1
  template:
    metadata:
      labels:
        app: demucs-rest
    spec:
      containers:
      - name: demucs-rest
        image: ash002019/demucs-rest:v1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_PORT
          value: "5000"
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: MINIO_HOST
          value: "minio:9000"
        - name: MINIO_USER
          value: "rootuser"
        - name: MINIO_PASSWD
          value: "rootpass123"
---