FROM xserrat/facebook-demucs:latest

RUN pip3 install --upgrade redis jsonpickle requests minio demucs

COPY worker-server.py /app/worker-server.py

WORKDIR /app

ENTRYPOINT	[ "python3", "-u", "worker-server.py" ]